### ISSUE TITLE
Springs don't link

### ISSUE THREAD

**Issue by Akitori** [jglrxavpok/Entity-Spring#1]
I get mod, intall it, try to link, doesn't link.

I update forge, try again, doesn't link.

I get the llibrary, try again, doesn't link.

I don't think its working atm.

**Comment by Akitori** [comment]
https://youtu.be/xRpmotiMx_w

**Comment by jglrxavpok** [comment]
Well that's embarrassing... I will try to fix it for tomorrow, sorry for
the inconvenience!

**Comment by jglrxavpok** [comment]
I have found the origin of the bug: the spring entity seem to wait 30s before being actually added to the world, no idea why.
I'll have to research further

**Comment by jglrxavpok** [comment]
Fixed in commit https://github.com/jglrxavpok/Entity-Spring/commit/cf0f96d13c16843e303f41ff3d3cae7bba5d9838
The spring entity was spawned in an unloaded chunk....

**Comment by Akitori** [comment]
How did you manage that?

**Comment by jglrxavpok** [comment]
In the update subroutine of spring entities, the entity is repositioned between the dominant and dominated entities. *But* on spawning, the position was not set, meaning the spring spawned at 0,0,0 which is unloaded most of the time; the game did not like that.
