### ISSUE TITLE
Minecart self propulsion

### ISSUE THREAD

**Issue by dannydjdk** [jglrxavpok/Entity-Spring#2]
I really love the concept of this mod and want to put it in my packs. However, the fact that connecting 2 minecarts causes them to move without any assistance kind of breaks it for me. In addition to making it difficult to work with, it kind of messes up the balance a bit.
Any chance that behavior could be changed?

**Comment by jglrxavpok** [comment]
I'll see what I can do about it but it may need quite some work

**Comment by jglrxavpok** [comment]
Fixed in 2.0.0
