### ISSUE TITLE
Consume Spring On Use

### ISSUE THREAD

**Issue by dannydjdk** [jglrxavpok/Entity-Spring#3]
When I use a spring to connect two entities, the spring remains in my inventory.
I believe that this is the intended behavior, so I'm requesting a feature that the spring be consumed on connecting two entities and perhaps drop when the entities are disconnected. Maybe there could be a second item to disconnect the entities, like a spring cutter or something like that.

**Comment by jglrxavpok** [comment]
Done in commit https://github.com/jglrxavpok/Entity-Spring/commit/f3c6542576fd085b469ba10a07905165f3590f85
