### ISSUE TITLE
Entity Blacklist/Whitelist

### ISSUE THREAD

**Issue by dannydjdk** [jglrxavpok/Entity-Spring#4]
I would love the ability to blacklist and/or whitelist certain entities in a config file. When building and testing a modpack, I might find that the ability to connect to certain entities messes with the balance of the pack or potentially causes bugs. Having the flexibility to blacklist such items or whitelist only specific items would be very useful.

**Comment by jglrxavpok** [comment]
I will add a config in the next release

**Comment by jglrxavpok** [comment]
Done in commit https://github.com/jglrxavpok/Entity-Spring/commit/3b51b1aff5e758a1b618c12e78e847568cd41274 :)

Default file: config/entity_spring_blacklist.txt
```
#Remove entities at your own risk!
minecraft:item
minecraft:xp_orb
minecraft:area_effect_cloud
minecraft:egg
minecraft:leash_knot
minecraft:painting
minecraft:arrow
minecraft:snowball
minecraft:fireball
minecraft:small_fireball
minecraft:ender_pearl
minecraft:eye_of_ender_signal
minecraft:potion
minecraft:xp_bottle
minecraft:item_frame
minecraft:wither_skull
minecraft:spectral_arrow
minecraft:shulker_bullet
minecraft:dragon_fireball
minecraft:dragon_fireball
minecraft:llama_spit
```
