### ISSUE TITLE
Suggestion: rigid springs

### ISSUE THREAD

**Issue by Ooles** [jglrxavpok/Entity-Spring#7]
Minecart self-propultion with springs is hard to fix, as i understand it, without rewriting carts physics. Well, here's quick potential fix: springs that repel two entities when they are too close.  Meaning, there's a optimal spring length where it doesn't excert force, when stretched it will try to pull things in and when compressed it will try to uncompress. Actual distances and forces will have to be chosen carefully or be tweakable to avoid oscillation.

**Comment by jglrxavpok** [comment]
I have been able to prevent Minecart self-propulsion by modelling an actual physical spring:
https://en.wikipedia.org/wiki/Spring_(device)#Physics The spring will now try to find an equilibrium!
https://github.com/jglrxavpok/Entity-Spring/commit/6023abb34ac690a7bde291dc007cf2ef786f755a

**Comment by Ooles** [comment]
Is that in 2.0.0? haven't tried it yet. Thanks!

**Comment by jglrxavpok** [comment]
Yes it is :)
https://minecraft.curseforge.com/projects/entity-spring/files/2552690
