### ISSUE TITLE
2.0.0 spams "Cannot Link Entity to itself" with PotionCore

### ISSUE THREAD

**Issue by Akitori** [jglrxavpok/Entity-Spring#8]
Version 2.0, minecraft forge 2654, springs keep spamming `cannot link to itself` despite whatever entity i'm looking at, vanilla or modded cart wise

**Comment by jglrxavpok** [comment]
Do you have other mods ? Especially ones that could interfere with the right click action, because the spring should no do anything unless you are right clicking

**Comment by Akitori** [comment]
I meant, no matter how many times i right click on the cart, it never links to other carts. Whenever i right click any cart/boat, it says, "Cannot link to itself."

**Comment by jglrxavpok** [comment]
You need to right click once on the first entity and then on the second. The item texture changes when you click on the first one

**Comment by Akitori** [comment]
I found the issue, its having to do with potioncore for some bizzare reason...

Odd? This issue wasn't occuring in the last update. Why would potioncore interfere at all...

**Comment by Akitori** [comment]
https://gfycat.com/FirmSpeedyCattle

**Comment by jglrxavpok** [comment]
This is indeed rather odd, I will need to investigate

**Comment by Akitori** [comment]
Its extremely odd as Potioncore adds no right click changes, all it modifies is the vanilla jump boost potion.

**Comment by Akitori** [comment]
alright, found the source of the bug. Its the way tmtravlr is making her reach modifier work.

(basically she makes reach affect entities too) turning that off allows me to use entity spring again

**Comment by MJRamon** [comment]
> alright, found the source of the bug. Its the way tmtravlr is making her reach modifier work.
> 
> (basically she makes reach affect entities too) turning that off allows me to use entity spring again

Bug is still here.
What exactly do I need to change? Thanks.

**Comment by Tmtravlr** [comment]
Hey, this is fixed in version 1.7 of potion core.
